### ISSUE TITLE
modificar tablas en Stats de "Maximum RMSD pair Comparison"

### ISSUE THREAD

**Issue by NPalopoli** [gstn-caruso/codnasq#101]
A la derecha de la visualización 3D en "Maximum RMSD pair Comparison" se muestran distintas comparaciones de valores para ese par máximo (RMSD, Structural similarity, Coverage, etc). 
Sería ideal mostrar esta tabla en tres columnas, que indiquen:
Primera columna: descripción de filas.
Segunda columna: datos del PDB query (tomados de info individual sobre el confórmero)
Tercera: datos del PDB target (también de tabla de confórmero)
Cuarta: datos de la comparación entre ambos.
Como molde para esto se puede ver la tabla "Information about pair maximum of confomrational diversity" en [CoDNaS-RNA](https://codnas.inf.pucp.edu.pe/detail/URS00000A7E81)

**Comment by NPalopoli** [comment]
Va un ejemplo de cómo quedaría, construido a partir del cluster 56 (http://codnasq.herokuapp.com/cluster/56):

![image](https://user-images.githubusercontent.com/1713937/86080290-f354af80-ba68-11ea-80bc-0c9927868c24.png)

Adjunto también la planilla donde hice ese esquema, por si ayuda: 
[20200630_tabla-stats-maxpair.ods.gz](https://github.com/gstn-caruso/codnasq/files/4849308/20200630_tabla-stats-maxpair.ods.gz)

Las primeras 6 filas se completan para cada confórmero individualmente. Las últimas siete provienen de la comparación del par máximo, aunque algunos valores que existen para cada elemento del par, se escriben en la columna individual de ese conformer.

**Comment by Nahuele** [comment]
esto casi está hecho con las ultimas modificaciones de hoy
