### ISSUE TITLE
Datos Erróneos en Pares Terciarios

### ISSUE THREAD

**Issue by Nahuele** [gstn-caruso/codnasq#104]
Los datos terciarios salian de las ultimas 3 columnas en la tabla de maximos

Por ejemplo el cluster "3vdm" 

Segun la tabla de maximos, los codigos_cadenas son:

... **4f9f_A** ; **3t5t_A** ;...

Sin embargo en el cluster figura 
**(3vdm, 3t5t)**

Corregir el campo **Maximum Tertiary Pair** Con el formato codigo_cadena

![image](http://i.imgur.com/Yt41GQM.png)

**Comment by gstn-caruso** [comment]
Ese dato lo estoy sacando de acá: https://github.com/gstn-caruso/codnasq/blob/master/app/controllers/cluster_controller.rb#L3Es decir, estoy agarrando todos los pares, los ordeno por RMSD y elijo el primero (https://github.com/gstn-caruso/codnasq/blob/21e8b49e561a6f51e433e88e39dd4b5247375d7e/app/models/cluster.rb#L5).

**Comment by NPalopoli** [comment]
@Nahuele de donde estás leyendo estos valores? 

Quiero leer los siguientes campos de la tabla cuaternaria:

`Cluster ID;Oligomeric State;PDB ID query;Biological Assembly query;PDB ID target;Biological Assembly target;RMSD`

Ejecuto este comando para levantar los valores. Los valores que usa Gastón están correctos (ver segunda y quinta líneas del output):

`grep 3vdm "website/DB-Q|05-07-19-15:50.csv" | cut -d';' -f1-6,16`
```
3vdm;2;3vdm;2;3vdn;1;0.47
3vdm;2;3vdm;2;4f9f;3;0.93
3vdm;2;3vdm;2;3t7d;1;1.26
3vdm;2;3vdm;2;4f96;1;0.32
3vdm;2;3vdm;2;3t5t;1;1.98
3vdm;2;3vdm;2;4f97;1;0.50
3vdm;2;3vdn;1;4f9f;3;0.91
3vdm;2;3vdn;1;3t7d;1;1.19
3vdm;2;3vdn;1;4f96;1;0.32
3vdm;2;3vdn;1;3t5t;1;1.52
3vdm;2;3vdn;1;4f97;1;0.44
3vdm;2;4f9f;3;3t7d;1;1.02
3vdm;2;4f9f;3;4f96;1;0.85
3vdm;2;4f9f;3;3t5t;1;1.34
3vdm;2;4f9f;3;4f97;1;0.96
3vdm;2;3t7d;1;4f96;1;1.21
3vdm;2;3t7d;1;3t5t;1;0.80
3vdm;2;3t7d;1;4f97;1;1.18
3vdm;2;4f96;1;3t5t;1;1.66
3vdm;2;4f96;1;4f97;1;0.26
3vdm;2;3t5t;1;4f97;1;1.43
```
Es posible que hayas visto mal los números Nahue, o se me escapa algo?

**Comment by Nahuele** [comment]
mmm no sé si entendí, quizás podemos hacer una llamada para esto.

Pero el cluster 3vdm tiene estos maximos terciarios: **4f9f_A** y **3t5t_A** 

![image](http://i.imgur.com/OymntEL.png)

**Comment by Nahuele** [comment]
> @Nahuele de donde estás leyendo estos valores?
> 
> Quiero leer los siguientes campos de la tabla cuaternaria:
> 
> `Cluster ID;Oligomeric State;PDB ID query;Biological Assembly query;PDB ID target;Biological Assembly target;RMSD`
> 
> Ejecuto este comando para levantar los valores. Los valores que usa Gastón están correctos (ver segunda y quinta líneas del output):
> 
> `grep 3vdm "website/DB-Q|05-07-19-15:50.csv" | cut -d';' -f1-6,16`
> 
> ```
> 3vdm;2;3vdm;2;3vdn;1;0.47
> 3vdm;2;3vdm;2;4f9f;3;0.93
> 3vdm;2;3vdm;2;3t7d;1;1.26
> 3vdm;2;3vdm;2;4f96;1;0.32
> 3vdm;2;3vdm;2;3t5t;1;1.98
> 3vdm;2;3vdm;2;4f97;1;0.50
> 3vdm;2;3vdn;1;4f9f;3;0.91
> 3vdm;2;3vdn;1;3t7d;1;1.19
> 3vdm;2;3vdn;1;4f96;1;0.32
> 3vdm;2;3vdn;1;3t5t;1;1.52
> 3vdm;2;3vdn;1;4f97;1;0.44
> 3vdm;2;4f9f;3;3t7d;1;1.02
> 3vdm;2;4f9f;3;4f96;1;0.85
> 3vdm;2;4f9f;3;3t5t;1;1.34
> 3vdm;2;4f9f;3;4f97;1;0.96
> 3vdm;2;3t7d;1;4f96;1;1.21
> 3vdm;2;3t7d;1;3t5t;1;0.80
> 3vdm;2;3t7d;1;4f97;1;1.18
> 3vdm;2;4f96;1;3t5t;1;1.66
> 3vdm;2;4f96;1;4f97;1;0.26
> 3vdm;2;3t5t;1;4f97;1;1.43
> ```
> 
> Es posible que hayas visto mal los números Nahue, o se me escapa algo?

Es que esa es la tabla de Quaternarios, no podes leer los datos terciarios de esa

**Comment by Nahuele** [comment]
fixed
