### ISSUE TITLE
create 'Not found' legend

### ISSUE THREAD

**Issue by Nahuele** [gstn-caruso/codnasq#36]
'not found' legend when the search is not successful

**Comment by gstn-caruso** [comment]
¿En dónde sería?
Actualmente no muestra ningún resultado, ¿decís algo así?
![image](https://user-images.githubusercontent.com/12160875/83825829-d5d23700-a6b0-11ea-889e-ebe8a68ca755.png)

**Comment by Nahuele** [comment]
Exacto! o sea, si yo busco 'asdasdadsad' en el campo de busqueda del home, ahora aparece como resultado una lista vacia, en vez de tener 'No results' como en la imagen
