### ISSUE TITLE
Add information to home page

### ISSUE THREAD

**Issue by NPalopoli** [gstn-caruso/codnasq#54]
The following could be added to the home page:

CoDNaS-Q is a high-quality collection of homo-oligomeric conformers obtained from the Protein Data Bank (PDB). It allows the exploration of conformational diversity and its determinants at the quaternary level, for a large number of proteins determined under different experimental conditions and from a wide variety of families and species. Find out more about CoDNaS-Q in the About and Help pages.

(include links to About and Help pages)

**Comment by gstn-caruso** [comment]
fixed in https://github.com/gstn-caruso/codnasq/commit/2be16b540cc335434294ce70e1eb4caf0dfd335b
