### ISSUE TITLE
Modification of columns, names and values

### ISSUE THREAD

**Issue by Nahuele** [gstn-caruso/codnasq#55]
**Conformer information** page

rename 'Longitude' -> 'Length'
rename 'Siblings' -> 'Other conformers'
mark somehow the row of opened conformer of the list

**Cluster information** 

remove 'Average RMSD Tertiary' (we dont have that data)
add 'Representative conformer type:' (with the title of the conformer. People wanna know what kind of cluster are they seeing)
add space between number and Å in Max RMSD Quaternary

**Maximum RMSD Pair information**

add chains of query and target for 'RMSD Tertiary' row (included in the csv file)

**Conformers in cluster**

delete 'Cluster' column
rename 'Longitude' -> 'Length'

**Statistics page**

resize images

**Comment by gstn-caruso** [comment]
### Pending: 
- mark somehow the row of opened conformer of the list
- add chains of query and target for 'RMSD Tertiary' row
