### ISSUE TITLE
Add chains of query and target for 'RMSD Tertiary' row in Cluster details page

### ISSUE THREAD

**Issue by gstn-caruso** [gstn-caruso/codnasq#57]
As part of #55.

The big question is, how to get the chains?

**Comment by NPalopoli** [comment]
Chains can be extracted from the conformer name by separating fields using
'_' (underscore) and getting the second element.
For example, '1rdx_A' corresponds to PDB ID '1rdx' and Chain ID 'A'.

Chains are included in the last file uploaded by Nahuel, along with the
maxRMSD.
