### ISSUE TITLE
add Gifs into index page

### ISSUE THREAD

**Issue by Nahuele** [gstn-caruso/codnasq#62]
Every clickeable gif image opens a list of the clusters in the group.

link to the gifs - https://drive.google.com/drive/folders/1nGCCIZ4kXaB9Gv4PIGeXeGj7IJNhGXQ9?usp=sharing

**Comment by gstn-caruso** [comment]
![image](https://user-images.githubusercontent.com/12160875/81860442-208ee200-953d-11ea-8c44-e87adf6e7f38.png)

**Comment by Nahuele** [comment]
No no, los Gifs vendrian en una card aparte, abajo de esa principal de busqueda. Quedaria algo como:
<div> **Search by type of movement:**

Gif1  Gif2  Gif3 </div>

Y lo que hace en realidad cada imagen, es una busqueda por tipo de movimiento, en vez de filtrar por especie, o nombre (ya esta hecho)
Cuando clickeas el gif seria lo mismo que poner en el filtro de busqueda avanzada 'buscar por grupo "a" ' por ejemplo.
