### ISSUE TITLE
Home - search - results

### ISSUE THREAD

**Issue by Nahuele** [gstn-caruso/codnasq#69]
El resultado de la búsqueda debería devolver 1 fila por cluster. Ese es el cluster que contenga un confórmero que cumpla con el criterio de búsqueda.

Actualmente arroja _1 fila por conformero del cluster_.

**Comment by gstn-caruso** [comment]
![image](https://user-images.githubusercontent.com/12160875/81860111-a8c0b780-953c-11ea-8cd4-8f70e0091236.png)

**Comment by Nahuele** [comment]
Ah no, perdón, ahí me fijé y creo que está bien como está, porque si yo busco un código o ingreso algo en el campo "all fields" me devuelve 1 cluster por linea, cosa que está bien.
Ahora que veo esa imagen, puede que haya un error, porque aparecen 4 lineas y codigos PDB, pero ese cluster tiene 5 codigos PDB adentro, está faltando el **1l3c** https://codnasq.herokuapp.com/cluster/1 
Lo mismo pasa con el siguiente cluster CQ2wzn, deberia tener 2 lineas y aparece una sola, creo que está excluyendo la última en todos los casos
