### ISSUE TITLE
URL routing del cluster

### ISSUE THREAD

**Issue by Nahuele** [gstn-caruso/codnasq#70]
Current version:

1) Si entramos al cluster 2vcq la URL es https://codnasq.herokuapp.com/cluster/146

New Version

1) Al entrar al cluster 2vcq la URL seria https://codnasq.herokuapp.com/cluster/CQ2vcq

**Comment by NPalopoli** [comment]
Siguiendo a esto, en el home el ejemplo "2vcq" dirige al cluster, no al confórmero. Debería decir entonces "CQ2vcq".

**Comment by gstn-caruso** [comment]
¿Todos los codnasq_id deberían ser CQ + el pdb ?

**Comment by Nahuele** [comment]
si, en realidad eso lo pensamos despues de hacer las tablas,
CQ + pdb id del cluster, asi como aparecen en la lista de resultados, tomar ese id y colocarlo en la url
