### ISSUE TITLE
Add maxRMSD quaternary

### ISSUE THREAD

**Issue by Nahuele** [gstn-caruso/codnasq#72]
agregar el valor del maxRMSD cuaternario a los clusters, así se puede ver en la vista de cluster y también en la vista de las tarjetas de la busqueda avanzada

**Comment by gstn-caruso** [comment]
Una pregunta, todos estos son los documentos que veo compartidos, ¿de dónde puedo obtener este dato?

![image](https://user-images.githubusercontent.com/12160875/83817773-03f94c00-a69c-11ea-9a69-0f0b2e2e5081.png)

**Comment by Nahuele** [comment]
Los datos de los maximos RMSD se podian obtener de dos formas:

1) Explorando todas las comparaciones de a pares de los conformeros  dentro del cluster deseado y seleccionar la fila que tenga el RMSD mas alto, y de ahi sacar todos los datos (pdb1, pdb2, ligandos1,ligandos2, estadisticas de la comparacion -ver imagen de wsp-)

2) O directamente usar la tabla de los maximos que esta en la carpeta maximosRMSD ,
el archivo [maxRMSD-Q|05-07-19-15:53.tar.gz](https://drive.google.com/file/d/1k_xkLTaI9PZo9Q79RnfvFC5dH_ETiYEt/view?usp=sharing) que ya agrege incluso el maxRMSD terciario, pdb1 y pdb2 terciario al final de las columnas
