### ISSUE TITLE
Mostrar Confórmeros en Cluster View

### ISSUE THREAD

**Issue by Nahuele** [gstn-caruso/codnasq#96]
Con la nueva actualización de los máximos se dejaron de ver los demás confórmeros dentro del cluster, solo muestra el par maximo.

imagen del cluster 
(https://codnasq.herokuapp.com/cluster/3vdm)

![conf](http://i.imgur.com/yuFveNZ.png)

**Comment by gstn-caruso** [comment]
¡Arreglado :smile: en producción!
