### ISSUE TITLE
Mostrar los campos que faltan en Cluster View

### ISSUE THREAD

**Issue by Nahuele** [gstn-caruso/codnasq#97]
Incluir los campos que faltan, la informacion se extrae de la tabla de maximos
Del PDB Query por ejemplo, aunque los dos son equivalentes.

![image](http://i.imgur.com/PeVg3SU.png)

**Comment by NPalopoli** [comment]
Agrego que, además de incluir "Maximum Tertiary Pair", deberíamos incluir
"Maximum Quaternary Pair". Son los mismos que en el par máximo que se
muestra debajo de la visualización 3D. No importa que se repita, está bueno
tenerlo en la tabla.

--
Nicolás Palopoli
Structural Bioinformatics Group
Universidad Nacional de Quilmes - CONICET
http://orcid.org/0000-0001-7925-6436
